### PR TITLE
Small change to pod-spec

### PR DESCRIPTION
**Pull request by loevborg**
I have removed 'SlideMenu/Source/Assets/*.{png}' from the s.source.files part of the pod spec, since this gives trouble when compiling the pod in your project, you get this warning: 

warning: no rule to process file '/Users/user/Documents/Git - iPhone Projects/Project/Pods/iOS-Slide-Menu/SlideMenu/Source/Assets/menu-button.png' of type image.png for architecture x86_64

..when trying to compile the project for iOS8.

The SlideMenu/Source/Assets is correctly part of the pod spec s.resources, so this should remove the warnings, and the pod should still work.

Hope you will have a look at this, and thanks for a great sliding menu, I use it in many of my projects!

### CODE REVIEW

**Comment by aryaxt** [comment]
Thanks a lot.
Will test this and merge to master

**Comment by gulsharan-pv** [comment]
@aryaxt Are you planning to accept this PR anytime soon?

**Comment by aryaxt** [comment]
@gulsharan-pv  Will merge this and release the new version this weekend

**Comment by gulsharan-pv** [comment]
Thanks @aryaxt!

**Comment by jonasman** [comment]
using the pods i cannot get the menu button to work. any ideas?

**Pull request merged**
